version: '3.8'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
  frontend:
    image: node:14
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: ["npm", "start"]
    ports:
      - "3000:3000"
